# Generated by Django 3.2 on 2021-04-28 12:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('isbn', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('publisher', models.CharField(max_length=300)),
                ('language', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='BookItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_date', models.DateTimeField()),
                ('pulication_date', models.DateTimeField()),
                ('borrowed_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Reserved', 'Reserved')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('book_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.bookdetails')),
            ],
        ),
    ]
