# Generated by Django 3.2 on 2021-04-28 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_bookdetails_bookdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_number', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rack_loaction', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='bookitem',
            name='location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='book.rack'),
            preserve_default=False,
        ),
    ]
