# Generated by Django 3.2 on 2021-04-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20210428_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetail',
            name='author',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookdetail',
            name='language',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rack',
            name='rack_number',
            field=models.CharField(max_length=100),
        ),
    ]
