# Generated by Django 3.2 on 2021-04-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20210428_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookitem',
            name='borrowed_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bookitem',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bookitem',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('Lost', 'Lost'), ('Loaned', 'Loaned')], max_length=10),
        ),
    ]
