# Generated by Django 3.2 on 2021-04-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20210428_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookitem',
            name='borrowed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookitem',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
