# Generated by Django 3.2 on 2021-04-28 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20210428_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField()),
                ('reserved_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.bookitem')),
            ],
        ),
    ]
