# Generated by Django 3.2 on 2021-04-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_book_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_reservation',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Completed', 'Completed'), ('None', 'None')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
