# Generated by Django 3.2 on 2021-04-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20210429_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetail',
            name='cover',
            field=models.ImageField(null=True, upload_to='covers/'),
        ),
    ]
