# Generated by Django 3.2 on 2021-04-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_checkout_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout_details',
            name='total_checkout',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
