# Generated by Django 3.2 on 2021-04-30 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_remove_book_lending_book_reservation_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_lending',
            name='return_date',
            field=models.DateTimeField(null=True),
        ),
    ]
