# Generated by Django 3.2 on 2021-10-09 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_alter_book_lending_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_lending',
            name='return_status',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('None', 'None')], default='No', max_length=10),
        ),
    ]
